### ISSUE TITLE
Makemigrations always displaying field info

### ISSUE THREAD

**Issue by adi-** [belug23/django-epiced#10]
When I am running `makemigrations` Django always displays

`content django.db.models.TextField [] {}`

Is it my error, or something to do with `django-epiced`?

**Comment by belug23** [comment]
Sorry for the late answer, I did not saw your question.

I've looked a little into it and it's a debugging print that is still in the code. It should not cuse any problem.

I'll do a fix later today.

Thanks for reporting it.
